In [4]:
import numpy
arr = numpy . array ([1 , 2, 3, 4, 5]) 
print ( arr )

import numpy as np
a = np.array([1, 2, 3, 4, 5]) 
print(a)
print(type(a))


[1 2 3 4 5]
[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
import numpy as np 
arr = np. array (42) 
print ( arr )
arr1 = np.array([1, 2, 3, 4, 5]) 
print(arr1)
arr2 = np.array([[1, 2, 3], [4, 5, 6]]) 
print(arr2)
arr3 = np.array([[[0, 1], [2, 3]], [[4, 5], [6, 7]]])


42
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [7]:
import numpy as np
a = np.array([(1 ,2 ,3)]) 
print(a.dtype)
arr = a.astype('float64') 
print(arr) 
print(arr.dtype)
s = np.array(['Ram','Robert','Rahim']) 
s.dtype


int32
[[1. 2. 3.]]
float64


dtype('<U6')

In [8]:
a = np.array([1, 2, 3, 4])
print(a + 1) 
print(a**2)
b = np.ones(4) + 1 
print(b)
b = np.zeros((3,3)) + 1
print(b)
c = np.eye(3)
d = np.eye(3, 2)
a = np.diag([1, 2, 3, 4]) 
a
print(a[2, 2])


[2 3 4 5]
[ 1  4  9 16]
[2. 2. 2. 2.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
3
